### ISSUE TITLE
请作者帮忙解答一下

### ISSUE THREAD

**Issue by YanpingDuan** [HowieYuan/easyexcel-method-encapsulation#4]
我copy你的代码下来，发现下载的Excel里面内容全部是空的，什么内容都没有，你的有这个问题吗？这是我的代码：
![2019-03-07 4 57 53](https://user-images.githubusercontent.com/48313773/53944387-3794a180-40fa-11e9-9386-a9c57e666cbb.png)

**Comment by HowieYuan** [comment]
我这边一切正常，你的 User 类有添加上注解了吗

**Comment by YanpingDuan** [comment]
> 我这边一切正常，你的 User 类有添加上注解了吗
已解决，感谢
